### ISSUE TITLE
Cad files available?

### ISSUE THREAD

**Issue by a2retro** [Retrotink/Apple-IIc-Portable#2]
Hi What was the CAD program you used and will you be adding the source files to the repo?
Thanks for sharing your work.

**Comment by Retrotink** [comment]
The STL Files are the CAD files for making the case.

**Comment by ibytergj** [comment]
STL files are good for printing but not that great for making modifications. Would it be possible to upload STEP files?

**Comment by Retrotink** [comment]
Sorry, I only have STL files. All pieces were created on Tinkercad

**Comment by a2retro** [comment]
Okay, thanks for checking. I will fork and see if I can find a way to convert to STEP. Also, I see you shared the location in TinkerCAD . Thanks

**Comment by a2retro** [comment]
I opened in TinkerCAD and saw there was an option to send to Fusion360. Trying that now. I use Eagle/Fusion360 for my cards designs so this might work out well.

**Comment by Retrotink** [comment]
I'm hoping to see lots of forks with different designs for different add-on options

**Comment by a2retro** [comment]
![image](https://github.com/Retrotink/Apple-IIc-Portable/assets/13440567/8d990bab-8b5a-4ba9-866e-97f13f2c60ef)

FYI, Most of the parts did not come through unfortunately so this will not be an option.

**Comment by Retrotink** [comment]
Ok, maybe it is just too much for 1, I can split up the pieces in Tinkercad and see if that helps?

**Comment by a2retro** [comment]
I think it has something to do with only primitive shapes can be passed to Fusion. Looking into alternatives to convert from STL. There’s nothing wrong with tinkercad per se it’s just that I’d rather not have to try and learn yet another program. 🙂

**Comment by ibytergj** [comment]
Just a FYI, the power and video covers converted to Fusion solids nicely. The battery, belt and LCD front bezel converted with a few issues. Needs additional work to fix the missing parts and combine some sections to make a cleaner model in Fusion. I have not been able to get a solid model from the LCD back bezel yet. Will keep you updated on progress.
